# In-Class Programming Activity, Day 8

##Nikhita Jain

```{r}
#Task 1, 1.

x = runif(100, min=20, max=70)
y = 5 + 3*x + 2*rnorm(100)
My_data = data.frame(x,y)

#Task 1, 2.

plot(My_data)

#Task 1, 3.

LL_line = function(params) {
  m = params[1]
  b = params[2]
  sigma = params[3]
  sum(log(dnorm(y - (m * x + b), sd = sigma)))
}
  
#Task 1, 4.
  
testA = LL_line(c(3,5,2))
testB = LL_line(c(4,1,10))

#Task 1, 5.

starting_params = c(4,1,10)
best = optim(starting_params, LL_line, control=list(fnscale = -1))
      
```

```{r}
#Task 2

load(url("http://tiny.cc/dcf/Taxi_trips.rda"))


taxi_likelihood= function(paramss){
  base_fare = paramss[1]
  per_mile= paramss[2]
  params = paramss[3]
  waiting_fare = with(Taxi_trips, fare_amount - (base_fare + per_mile* trip_distance))
  sum(log(dexp(abs(waiting_fare), params)))
  
}

testA= taxi_likelihood(c(2.00, 4.00, 1/3))
testA

starting_params = c(2.00, 4.00, 1/3)
best = optim(starting_params, taxi_likelihood, control=list(fnscale = -1))
best

plot(Taxi_trips$fare_amount, Taxi_trips$trip_distance)
abline(best$base_fare, best$per_mile, col="red")
abline
```

## Test statements

```{r}
scoreActivity::score253(8)
```